
databaseURL = "postgresql://localhost:5432/rds_provisioner"

[logging]
level = "debug"
jsonLogs = false

[server]
bindAddress = "127.0.0.1:8081"

[aws]
serviceConfigProfile = "personal"
accountId = "283492314377"

[aws.rds]
supportedInstanceClasses = ["db.t2.micro"]
supportedEngines = ["postgres:12.10"]
subnetGroupNames = ["project-rds-copy-vpc-rds-subnet-group"]
allowedStorageSizeGBRange = "5:10"
masterUsername = "superuser"
masterPassword = "=29#2VwcBJf3hh#9"

[backup]
s3_bucket = "librodo-db-backups"

[dbregistry]
[[databases]]
dbName = "source_db"
host = "localhost"
port = 5432
user="admin"
password="GXAg*93&L6*PPjAP"

[[databases]]
dbName = "another_source_db"
host = "localhost"
port = 5432
user="admin"
password="GXAg*93&L6*PPjAP"




