[logging]
level = 'debug'
jsonLogs = false

[server]
bindAddress = '127.0.0.1:8081'

[aws]
serviceConfigProfile = ''

[aws.rds]
masterUsername = 'xxx'
masterPassword = ''

[backup]
s3_bucket = "librodo-db-backups"

[dbregistry]
[[databases]]
dbName = "source_db"
host = "localhost"
port = 5432
user="miketatari"
password=""

[[databases]]
dbName = "another_source_db"
host = "localhost"
port = 5432
user="miketatari"
password=""




